export const dataAlmacenes=[
  { "PLAZA": "02", "COD_ALM": "106", "NOM_ALM": "GUASAVE" },
  { "PLAZA": "05", "COD_ALM": "109", "NOM_ALM": "NAVOJOA" },
  { "PLAZA": "07", "COD_ALM": "005", "NOM_ALM": "EL ROSARIO" },
  { "PLAZA": "06", "COD_ALM": "006", "NOM_ALM": "SAN QUINTIN" },
  { "PLAZA": "08", "COD_ALM": "011", "NOM_ALM": "DELICIAS" },
  { "PLAZA": "00", "COD_ALM": "1", "NOM_ALM": "CULIACAN" },
  { "PLAZA": "01", "COD_ALM": "1", "NOM_ALM": "CULIACAN" },
  { "PLAZA": "04", "COD_ALM": "1", "NOM_ALM": "CULIACAN" },
  { "PLAZA": "27", "COD_ALM": "1", "NOM_ALM": "CULIACAN" },
  { "PLAZA": "97", "COD_ALM": "1", "NOM_ALM": "CULIACAN" },
  { "PLAZA": "99", "COD_ALM": "1", "NOM_ALM": "CULIACAN" },
  { "PLAZA": "03", "COD_ALM": "115", "NOM_ALM": "LA PAZ" },
  { "PLAZA": "11", "COD_ALM": "018", "NOM_ALM": "OJOS NEGROS" },
  { "PLAZA": "96", "COD_ALM": "018", "NOM_ALM": "OJOS NEGROS" },
  { "PLAZA": "98", "COD_ALM": "018", "NOM_ALM": "OJOS NEGROS" },
  { "PLAZA": "09", "COD_ALM": "019", "NOM_ALM": "GUADALAJARA" },
  { "PLAZA": "10", "COD_ALM": "022", "NOM_ALM": "HERMOSILLO" },
  { "PLAZA": "13", "COD_ALM": "025", "NOM_ALM": "CABORCA" },
  { "PLAZA": "14", "COD_ALM": "304", "NOM_ALM": "ISLA DEL BOSQUE ESCUINAPA" },
  { "PLAZA": "15", "COD_ALM": "355", "NOM_ALM": "SANTIAGO NAYARIT" },
  { "PLAZA": "16", "COD_ALM": "402", "NOM_ALM": "COLIMA" },
  { "PLAZA": "17", "COD_ALM": "404", "NOM_ALM": "CD. OBREGON" },
  { "PLAZA": "18", "COD_ALM": "406", "NOM_ALM": "GUAMUCHIL" },
  { "PLAZA": "19", "COD_ALM": "408", "NOM_ALM": "NAVOLATO" },
  { "PLAZA": "20", "COD_ALM": "410", "NOM_ALM": "CORTAZAR,GTO" },
  { "PLAZA": "21", "COD_ALM": "415", "NOM_ALM": "LOS MOCHIS" },
  { "PLAZA": "22", "COD_ALM": "427", "NOM_ALM": "PUEBLA" },
  { "PLAZA": "23", "COD_ALM": "429", "NOM_ALM": "MORELOS" },
  { "PLAZA": "24", "COD_ALM": "431", "NOM_ALM": "VERACRUZ" },
  { "PLAZA": "25", "COD_ALM": "433", "NOM_ALM": "MICHOACAN" },
  { "PLAZA": "12", "COD_ALM": "400", "NOM_ALM": "LA CRUZ" },
  { "PLAZA": "26", "COD_ALM": "033", "NOM_ALM": "CHINITOS" }
]